apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"pvc-rafa-cluster","namespace":"default"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"1Gi"}}}}
  creationTimestamp: "2020-04-30T04:08:11Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: pvc-rafa-cluster
  namespace: default
  resourceVersion: "64070"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/pvc-rafa-cluster
  uid: 6d2eb8dc-eb56-427b-af3a-e35dac9d4d2b
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
status:
  phase: Pending
