apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rafa-cluster
  region: us-west-2

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2  
    minSize: 2
    maxSize: 2
    iam:
        withAddonPolicies:
          externalDNS: true        
  
