apiVersion: v1
kind: Service
metadata: 
    name: flask-cluster-ip-service
spec: 
    type: ClusterIP
    selector:
        app: flask
    ports: 
        -   port: 5000
            targetPort: 5000
            