apiVersion: v1
kind: Service
metadata: 
    name: static-cluster-ip-service
spec: 
    type: ClusterIP
    selector:
        app: nginx
    ports: 
        -   port: 80
            targetPort: 80
            